[project]
name = "obsidian-bot"
version = "0.1.0"
description = "This is a Telegram bot that allows you to add log to your daily log in Obsidian."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "python-telegram-bot>=21.5",
]
